global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "imgproxy-job"
    static_configs:
      - targets: ["imgproxy:9100"]
      
  - job_name: 'imgproxy-proxy-job'
    scrape_interval: 5s
    static_configs:
      - targets: ['proxy:8080']
    metrics_path: '/metrics'

  # You can add more scrape targets here if needed